name: vhs
title: vhs
summary: Write terminal GIFs as code
adopt-info: vhs
description: |
  Write terminal GIFs as code for integration testing and demoing your CLI tools.

license: MIT
source-code: https://github.com/charmbracelet/vhs
issues: https://github.com/popey/vhs/issues
contact: https://github.com/popey/vhs
 
base: core24
grade: stable
confinement: classic
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]

apps:
  vhs:
    command: bin/vhs

parts:
  vhs:
    source: https://github.com/charmbracelet/vhs
    source-type: git
    plugin: go
    build-snaps:
      - go
    
    stage-snaps:
      - ttyd
      - ffmpeg
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
